Completed project
bx44/mint.com-signup-page pull request #1
Opened 2019-11-27 17:57 UTC by bx44

2019-11-27 23:24 UTC, bx44 commented
This project I had to do it by myself, because my partner left he program.

2019-11-27 23:33 UTC, MauricioRobayo requested changes
Looking very well, congratulations! 

Just a few minor issues before continuing:

- [ ] Make the README.md more descriptive.
- [ ] Validate `index.html` and fix the `errors`: https://validator.w3.org/#validate_by_input.

[OPTIONAL] Take a look at the `header`, `nav`, `main` and `footer` tags... try to use them instead of `div`s tags where appropriate.

**Status**: Request changes.

2019-11-27 23:33 UTC, MauricioRobayo commented on index.html
> +    <title>YouTube video page</title>
This is not YouTube 😄 .

2019-11-27 23:33 UTC, MauricioRobayo commented on index.html
> +					<input type="email" name="email" required>
You can add an `id` attribute that matches the `for` attribute of the `label` so they are associated together: https://www.youtube.com/watch?v=HS4bvh_59hU

2019-11-28 00:03 UTC, nikasulo approved these changes
# Summary
Really nice work! You have one more error to correct courtesy of the HTML validator. I am putting some trust in you that you will correct it before you merge this PR, that being said, I am approving your project.

### See you at the top! :rocket:

2019-11-28 00:11 UTC, merged